package com.fourweather.learn.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fourweather.learn.entity.CityWeaInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CITY_WEA_INFO".
*/
public class CityWeaInfoDao extends AbstractDao<CityWeaInfo, Long> {

    public static final String TABLENAME = "CITY_WEA_INFO";

    /**
     * Properties of entity CityWeaInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Pos = new Property(0, Long.class, "pos", true, "_id");
        public final static Property Cid = new Property(1, String.class, "cid", false, "CID");
        public final static Property JsonString = new Property(2, String.class, "jsonString", false, "JSON_STRING");
    }


    public CityWeaInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CityWeaInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CITY_WEA_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: pos
                "\"CID\" TEXT UNIQUE ," + // 1: cid
                "\"JSON_STRING\" TEXT);"); // 2: jsonString
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CITY_WEA_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CityWeaInfo entity) {
        stmt.clearBindings();
 
        Long pos = entity.getPos();
        if (pos != null) {
            stmt.bindLong(1, pos);
        }
 
        String cid = entity.getCid();
        if (cid != null) {
            stmt.bindString(2, cid);
        }
 
        String jsonString = entity.getJsonString();
        if (jsonString != null) {
            stmt.bindString(3, jsonString);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CityWeaInfo entity) {
        stmt.clearBindings();
 
        Long pos = entity.getPos();
        if (pos != null) {
            stmt.bindLong(1, pos);
        }
 
        String cid = entity.getCid();
        if (cid != null) {
            stmt.bindString(2, cid);
        }
 
        String jsonString = entity.getJsonString();
        if (jsonString != null) {
            stmt.bindString(3, jsonString);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CityWeaInfo readEntity(Cursor cursor, int offset) {
        CityWeaInfo entity = new CityWeaInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // pos
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // jsonString
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CityWeaInfo entity, int offset) {
        entity.setPos(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setJsonString(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CityWeaInfo entity, long rowId) {
        entity.setPos(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CityWeaInfo entity) {
        if(entity != null) {
            return entity.getPos();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CityWeaInfo entity) {
        return entity.getPos() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
